/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.ui.tests;

import com.google.inject.Injector;
import org.ccsl.textual.ui.internal.TextualActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TextualUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TextualActivator.getInstance().getInjector("org.ccsl.Textual");
	}

}
