/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.ui;

import com.google.inject.Injector;
import org.ccsl.textual.ui.internal.TextualActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextualExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TextualActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TextualActivator activator = TextualActivator.getInstance();
		return activator != null ? activator.getInjector(TextualActivator.ORG_CCSL_TEXTUAL) : null;
	}

}
