/*
 * generated by Xtext 2.22.0
 */
package org.ccsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TextualStandaloneSetup extends TextualStandaloneSetupGenerated {

	public static void doSetup() {
		new TextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
