/*
 * generated by Xtext 2.22.0
 */
package org.ccsl;

import org.ccsl.QualifiedNameProvider.QualifiedNameProvider;
import org.ccsl.scoping.TextualScopeProvider;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextualRuntimeModule extends AbstractTextualRuntimeModule  {
	
	
	 public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
	        return QualifiedNameProvider.class;
	    }
	 
	 public Class<? extends IScopeProvider> bindIScopeProvider() {
	        return TextualScopeProvider.class;
	    }
	
}
