/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.validation;

import ccsl.elements.Element;
import ccsl.AtomicRule;

import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.EcoreUtil2;
import ccsl.context.Context;

import ccsl.ccslPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class TextualValidator extends AbstractTextualValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					TextualPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
}
