/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TextualUiModule extends AbstractTextualUiModule {

	public TextualUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
