<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="faultTypeDescription" nsURI="http://www.example.org/ccsl/faultTypeDescription"
    nsPrefix="faultTypeDescription">
  <eClassifiers xsi:type="ecore:EClass" name="InjectionAction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="ecore:EClass ../../org.ccsl.metamodel/model/ccsl.ecore#//elements/Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InjectionStrategy" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FaultTypeDescription" eSuperTypes="../../org.ccsl.metamodel/model/ccsl.ecore#//Root">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="ecore:EClass ../../org.ccsl.metamodel/model/ccsl.ecore#//AtomicRule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" lowerBound="1"
        upperBound="-1" eType="#//InjectionAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategies" lowerBound="1"
        upperBound="-1" eType="#//InjectionStrategy" containment="true"/>
  </eClassifiers>
  <eSubpackages name="action" nsURI="http://www.example.org/ccsl/faultTypeDescription/action"
      nsPrefix="action">
    <eClassifiers xsi:type="ecore:EClass" name="DeleteAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="MoveScopeUpAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteInfixOperatorAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeLiteralValueAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteRandomStatementAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceVariableAccessAction"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReplaceArithmeticOperatorAction">
      <eStructuralFeatures xsi:type="ecore:EReference" name="replaceMap" lowerBound="1"
          upperBound="-1" eType="#//action/ArithmeticOperatorMap" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArithmeticOperatorMap">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="oldArithmeticOperator"
          eType="ecore:EEnum ../../org.ccsl.metamodel/model/ccsl.ecore#//elements/expressions/ArithmeticOperator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="newArithmeticOperator"
          eType="ecore:EEnum ../../org.ccsl.metamodel/model/ccsl.ecore#//elements/expressions/ArithmeticOperator"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="strategy" nsURI="http://www.example.org/ccsl/faultTypeDescription/strategy"
      nsPrefix="strategy">
    <eClassifiers xsi:type="ecore:EClass" name="AllStrategy"/>
  </eSubpackages>
</ecore:EPackage>
