/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.parser.antlr;

import com.google.inject.Inject;
import org.ccsl.parser.antlr.internal.InternalTextualParser;
import org.ccsl.services.TextualGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TextualParser extends AbstractAntlrParser {

	@Inject
	private TextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTextualParser createParser(XtextTokenStream stream) {
		return new InternalTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Rule";
	}

	public TextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
