/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.ccsl.TextualRuntimeModule;
import org.ccsl.TextualStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TextualIdeSetup extends TextualStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TextualRuntimeModule(), new TextualIdeModule()));
	}
	
}
