/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTextualScopeProvider extends DelegatingScopeProvider {
}
