/*
 * generated by Xtext 2.22.0
 */
package org.ccsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTextualValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/filters"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/namedElements/complexType"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/expressions"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/datatype"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/expressions/accesses"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/namedElements/variable"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/namedElements"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/context"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/expressions/annotation"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements/import"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/namedElements/method"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements/controlFlow"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements/tryCatch"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/expressions/invocations"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/expressions/arrays"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements/assignment"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/ccsl/elements/statements/literals"));
		return result;
	}
}
